CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c99
INPUT_FILE=./hexdump.c
OUTPUT_FILE=../../../bin/chapter_22/programming_projects/06/hexdump

hexdump:
	$(CC) $(CFLAGS) -o  $(OUTPUT_FILE) $(INPUT_FILE)


