CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c99
FILE_1=../../../bin/chapter_22/programming_projects/19/unix2win
FILE_2=../../../bin/chapter_22/programming_projects/19/win2unix

all: unix2win win2unix

unix2win:
	$(CC) -o  $(FILE_1) unix2win.c $(CFLAGS)

win2unix:
	$(CC) -o  $(FILE_2) win2unix.c $(CFLAGS)
