CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c99
INPUT_FILE=./06.c
OUTPUT_FILE=../../../bin/chapter_23/programming_projects/06

01:
	$(CC) $(CFLAGS) -o  $(OUTPUT_FILE) $(INPUT_FILE)

sample:
	echo -e "Hello\tWorld\nThis is a test.\x01\x02" > sample.txt
