CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c99
INPUT_FILE=./xor.c
OUTPUT_FILE=../../../bin/chapter_22/programming_projects/05/xor

xor:
	$(CC) $(CFLAGS) -o  $(OUTPUT_FILE) $(INPUT_FILE)

clean:
	rm ./output*.dat
