CC=gcc
CFLAGS=-Wall -Wextra -Werror -Wpedantic -std=c99
INPUT_FILE=./viewmemory.c
OUTPUT_FILE=../../bin/chapter_20/view_memory/viewmemory

viewmemory:
	$(CC) $(CFLAGS) -o  $(OUTPUT_FILE) $(INPUT_FILE)
